= OAuth 認証許可種別
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: http, 認証, セキュリティ, ユーザ, コネクタ, Anypoint, Studio, oauth

OAuth コンシューマ (クライアントアプリケーション) が OAuth サービスプロバイダから保護されたリソースへのアクセス権を取得するために使用できる 4 つの認証許可種別があります。

* <<authorization-code>>

* <<implicit>>

* <<resource-owner-password-credentials>>

* <<client-credentials>>

OAuth 認証フレームワークについては、RFC 6749 の「OAuth 2.0 認証フレームワーク」を参照してください。

////
For more information about OAuth roles and the OAuth dance, see the xref:mule-secure-token-service.adoc[Mule Secure Token Service] topic.
////

[[authorization-code]]
== 認証コード

認証コード許可種別では、認証サーバ (保護されたリソースにアクセスするための権限を確認して付与する) とリソースサーバ (保護されたリソースへのアクセスを提供する) を使用します。独立したサーバとして記述されていますが、認証サーバとリソースサーバは同じ Mule サーバに存在します。認証コード許可種別を使用する場合、クライアントアプリケーションは、保護されたリソースへのアクセス権を付与するトークンを要求する前に、サービスプロバイダに認証コードを要求する必要があります。

認証コード許可種別は、認証されていないパーティ (リソースオーナーを含む) に公開することなくクライアントを認証してアクセストークンを転送するため、特に安全です。

認証コード許可種別を使用する OAuth ダンスは次のように機能します。

. クライアントアプリケーションはサービスプロバイダによって制御されている、保護されたリソースを使用するために、リソースへのアクセス要求を開始します。

. クライアントアプリケーションは、サービスプロバイダの認証サーバをコールし、サービスプロバイダの登録済みクライアントであることを確認するためのクライアント ID を提供します。

. クライアントアプリケーションは、サービスプロバイダによって提供されるログインページを使用して、サービスプロバイダの認証を受けます。

. クライアント ID が有効である (クライアントアプリケーションが以前にサービスプロバイダに登録されている) ことを確認し、リソースオーナーのログイン情報を認証したら、サービスプロバイダは認証コードを返します。

. クライアントアプリケーションは、認証サーバをもう一度コールし、認証コード、クライアント ID (再度)、クライアントシークレットを提供します。

. サービスプロバイダは、アクセストークンを返します。

. クライアントアプリケーションは、リソースサーバをコールし、保護されたリソースを要求するためのアクセストークンを提供します。

. サービスプロバイダは、保護されたリソースを提供します。


[[implicit]]
== 暗黙的

認証コード許可種別と同様に、暗黙的許可種別には認証サーバとリソースサーバが関与します。ただし、認証コードとクライアントシークレットを使用してクライアントアプリケーションを認証するための追加手順を実行する代わりに、サービスプロバイダは次の作業を行います。

* クライアント ID に基づいてクライアントを認証する。

* 保護されたリソースにアクセスするためのアクセストークンを提供する。

暗黙的許可種別は、Javascript などのスクリプト言語を使用するブラウザクライアントのパフォーマンスを最適化します。ただし、この許可種別では、アクセストークンをリソースオーナーまたはリソースオーナーのユーザエージェントに公開できます。

暗黙的許可種別を使用する OAuth ダンスは次のように機能します。

. クライアントアプリケーションは、サービスプロバイダの認証サーバをコールし、サービスプロバイダの登録済みクライアントであることを確認するためのクライアント ID を提供します。

. クライアントアプリケーションは、サービスプロバイダによって提供されるログインページを使用して、リソースオーナーがサービスプロバイダに対してクライアントアプリケーションを認証するように要求します。

. クライアント ID が有効である (クライアントアプリケーションが以前にサービスプロバイダに登録されている) ことを確認し、リソースオーナーのログイン情報を認証したら、サービスプロバイダはアクセストークンを返します。

. クライアントアプリケーションは、リソースサーバをコールし、保護されたリソースを要求するためのアクセストークンを提供します。

. サービスプロバイダは、保護されたリソースを提供します。

[[resource-owner-password-credentials]]
== リソースオーナーパスワードログイン情報

リソースオーナーパスワードログイン情報許可種別を使用する場合、クライアントアプリケーションは、リソースオーナーがサービスプロバイダのログイン情報を共有するように要求します。次に、クライアントアプリケーションは、それらのログイン情報を使用して、サービスプロバイダにアクセスし、リソースオーナーのアカウントにアクセスします。サービスプロバイダは、有効なログイン情報を受け入れて、リソースオーナーのアカウントへのフルアクセス権をクライアントアプリケーションに付与します。

この認証種別は、安全なアクセスログイン情報の共有を犠牲にしてパフォーマンスを最適化します。リソースオーナーは、クライアントアプリケーションが非公開データへのアクセス権を共有しないことを信頼する必要があります。

リソースオーナーパスワードログイン情報許可種別を使用する OAuth ダンスは次のように機能します。

. リソースオーナーは、アクセスログイン情報をクライアントアプリケーションに提供します。

. クライアントアプリケーションは、サービスプロバイダをコールしてアクセストークンを要求します。クライアントは、コール時にサービスプロバイダの登録済みクライアントであることを確認するためのクライアント ID を提供します。保護されたリソースのアクセスログイン情報も提供します。

. サービスプロバイダは、クライアントアプリケーションを認証し、アクセスログイン情報を検証します。次に、アクセストークンを発行します。

. クライアントアプリケーションは、リソースサーバをコールし、保護されたリソースへのアクセスを要求するためのアクセストークンを提供します。

. サービスプロバイダは、保護されたリソースを提供します。

[[client-credentials]]
== クライアントログイン情報

クライアントログイン情報許可種別を使用する場合、クライアントアプリケーションは、特定のリソースオーナーに関連付けられていないデータへのアクセスを要求します。この許可種別では、サービスプロバイダはクライアントが有効であるかどうかのみを検証する必要があります。この種別の OAuth インタラクションは、2 つの役割 (サービスプロバイダとクライアントアプリケーション) のみが関与するため「2 本足の OAuth」と呼ばれることがあります。  他の 3 つの認証種別は、3 番目の役割 (リソースオーナー) が関与します。そのため、「3 本足の OAuth」と呼ばれることがあります。

通常、クライアントログイン情報許可種別は、クライアントがリソースオーナーでもある場合に適用されます。

クライアントログイン情報許可種別を使用する OAuth ダンスは次のように機能します。

. クライアントアプリケーションは、認証サーバをコールし、サービスプロバイダの登録済みクライアントであることを確認するためのクライアント ID を提供します。

. クライアント ID が有効である (クライアントアプリケーションが以前にサービスプロバイダに登録されている) ことを確認しら、サービスプロバイダはアクセストークンを返します。

. クライアントアプリケーションは、リソースサーバをコールし、保護されたリソースを要求するためのアクセストークンを提供します。

. クライアントアプリケーションは、保護されたリソースを取得します。

== 関連情報

* xref:mule-secure-token-service.adoc[Mule セキュアトークンサービス] 
