= ビジネスイベント
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Anypoint, Studio, esb, ビジネスイベント

Mule アプリケーションは、ビジネストランザクションを処理するフローおよびメッセージプロセッサに関するビジネスイベント情報を収集できます。この情報には、トランザクションの実行時間、エラー、結果 (正常に完了または失敗)、メッセージペイロード情報などが含まれます。

* トランザクション (フローレベルイベントグルーピング): システムのビジネスビューに対応することが多い関連イベントの倫理グルーピング。

* イベント (コンポーネントレベルイベント): トランザクションの低レベルの詳細。イベントは、メッセージプロセッサとコネクタにマップされます。イベントは、例外やカスタムイベントの場合もあります。カスタムイベントを除くすべてのイベントは、デフォルトイベントとみなされます。

== ビジネスイベント設定

ビジネスイベントは、いくつかの方法で有効化および作成できます。

* Choice ルータなどのコンポーネント: ビジネスイベントを有効化できる。
* Custom Business Event コンポーネント: カスタムイベントを設定して、特定のペイロード情報をキャプチャする。また、一部のデフォルトイベントは Mule サーバによって自動的に生成されます。

== ビジネスイベントの監視

Runtime Manager のインサイトを有効にして、これらのイベントを実行時に監視できます。これらのイベントは、失敗の根本原因を分析したり、パフォーマンスのボトルネックを特定したり、会社の手続きに準拠しているかどうかをテストしたりするのに役立ちます。

特定のデフォルトイベントは、インサイトが有効になると自動的に追跡されますが、他のイベントを追跡するには、アプリケーションで有効にする必要があります。

バッチプロセッサでは、ビジネスイベントの使用がサポートされません。

== ビジネスイベントの設定

Mule では、2 つの方法でビジネスイベント追跡を設定できます。

* フロー内の特定のポイントで Custom Business Event を設定する。
* フローまたはフロー内の特定のメッセージプロセッサ/コネクタのデフォルトイベント追跡を有効にする。

カスタムイベント追跡は、Custom Business Event 要素でサポートされています。カスタムイベントを設定すると、常に追跡されます。カスタムイベントでは、ビジネスに関連するフローの高レベルアクティビティを追跡できます。

デフォルトイベント追跡は、すべてのコネクタと一部のメッセージプロセッサでサポートされています。これらの要素のデフォルトイベントを有効にすると、実行時に高度なデバッグを実施できます。
