= 継続的インテグレーション
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: ビルド, デプロイ, テスト, Maven, ci, 継続的インテグレーション, 継続的, インテグレーション

プロジェクトの継続的インテグレーション (CI) のニーズは、非常に重要です。Maven をビルドツールとして使用すると、プロジェクトの変更ごとにトリガされるビルドを作成し、その単体テストと機能テストをすべて自動的に実行できます。

CI の利点は次のとおりです。

* ソフトウェア開発ライフサイクルの問題を早期の通知できる。
* リリース前にコードを完全にテストできる。
* 適切にテストされた分岐により、マスタ分岐へのマージに成功しやすくなる。

== 継続的インテグレーションの目的

CI システムは、次のすべての作業を行います。

. プロジェクトのソースコード管理システムへの新規コミットをリスンする。CI システムは、多数の分岐の新規コミットを監視します。ポーリングを使用して新規コミットを検索したり、管理システムでコミットをプログラムに通知するイベントをトリガしたりできます
. 最新の分岐を中央サーバに取り込む。
. 中央サーバでビルドジョブを作成する。
. Sandbox でプロジェクトをコンパイル、テスト、パッケージ化、デプロイしてプロジェクトが正常に機能することを確認する設定可能な単体テストとインテグレーションテストをコードベースで実行する。
. リポジトリにアーティファクトを保存する。
. 各ビルドの結果を表示する。
. ビルドを本番にデプロイする。

これらのツールについては、それぞれの Web サイトを参照してください。

== MuleSoft CI ツール

以下を使用して、Mule アプリケーションをデプロイできます。

* xref:api-manager::getting-started-proxy.adoc[API Manager]
* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager エージェント]

xref:2.1@munit::index.adoc[MUnit 単体テスト]を使用して、機能テストを作成できます。

mule-maven-plugin では、以下へのデプロイメントがサポートされています。

* CloudHub
* Anypoint Runtime Manager
* Runtime Fabric
* Mule エージェント
* ローカルインスタンス

Jenkins や Maven を使用する CI の完全な例については、&#8203;https://training.mulesoft.com/course-catalog[MuleSoft トレーニングサイト]の「Anypoint Platform Development: Advanced (Anypoint Platform 開発: 上級)」クラスを参照してください。トレーニングサイトには、関連するクラスや認定試験もあります。

== 外部 CI ツール

一般的な CI ツールを次に示します。

* Jenkins
* Hudson
* TeamCity
* Bamboo

これらのツールについては、それぞれの Web サイトを参照してください。

== インテグレーションの注意事項

機能テストケースでコネクタを使用する場合、継続的なビルドサーバで発生する可能性のある潜在的なポートの競合に注意してください。

デプロイ可能な対象が Mule アプリケーションではなく Web アプリケーションの場合、Junit インテグレーションテストランナーを使用して機能テストを実行し、ポートの競合を回避することを検討してください。

== 関連情報

* xref:using-maven-with-mule.adoc[Mule での Maven のサポート]
* xref:2.1@munit::index.adoc[MUnit 単体テスト]
