= 手動によるクラスタの作成および管理
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: クラスタ, デプロイ

*_Enterprise Edition_*

このページでは、手動によるクラスタの作成および設定について説明します。クラスタを作成および管理する方法は 3 つあります。

* Mule 管理コンソールのグラフィカルインターフェースを使用する
* Runtime Manager を使用する - 詳細は、xref:runtime-manager::managing-servers.adoc#create-a-cluster[「Creating and Managing Clusters (クラスタの作成および管理)」]を参照してください。
* 手動で設定ファイルを使用する


[CAUTION]
====
*複数の方法を組み合わせてクラスタを管理しないでください*

手動でクラスタを作成する場合は、管理コンソールで管理しないでください。管理コンソールでは、手動で作成されたクラスタを認識できないため、クラスタ設定が上書きされます。
====

[NOTE]
====
クラスタ内のすべてのノードでエージェントバージョンを同じにする必要があります。
====

== 手動でクラスタを作成する

設定ファイルを使用して手動でクラスタを作成する手順は、次のとおりです。

. ノードが実行されていないことと、Mule Runtime サーバが停止していることを確認します。
. ノードの `$MULE_HOME/.mule` ディレクトリ内に `mule-cluster.properties` という名前のファイルを作成します。
. パラメータ = 値のペア (1 行に 1 つ) を使用してファイルを編集します。以下の例を参照してください。
+
*注意*: `mule.clusterId` と `mule.clusterNodeId` は、プロパティファイルに存在している必要があります。
+
[source,text,linenums]
----
...
mule.cluster.nodes=192.168.10.21,192.168.10.22,192.168.10.23
mule.cluster.multicastenabled=false
mule.clusterId=<Cluster_ID>
mule.clusterNodeId=<Cluster_Node_ID>
...
----
+
. クラスタに含めるすべての Mule サーバでこの手順を繰り返します。
. ノードの Mule サーバを開始します。

使用可能なパラメータの完全なリストについては、「<<クラスタ設定パラメータ>>」を参照してください。

== 手動でクラスタを管理する

手動で管理できるのは、Mule 管理コンソールで管理されていない、手動で作成されたクラスタのみです。

クラスタノードの設定を手動で変更する手順は、次のとおりです。

. ノードの Mule サーバを停止します。

. 必要に応じてノードの `mule-cluster.properties` を編集し、ファイルを保存します。

. ノードの Mule サーバを再起動します。

[CAUTION]
====
*ノード間の一貫性を確保してください*

設定ファイルで適用するオプションがすべてのクラスタノードで有効であることを確認します。この作業を行わないと、クラスタ設定が破損し、クラスタが誤って無効になる可能性があります。
====

=== クォーラム管理

 _手動で設定したクラスタ_ を管理する場合、クラスタが稼働するのに必要なマシンの最小クォーラムを設定できるようになりました。

ネットワークをパーティション分割する場合、デフォルトでクラスタを使用できます。ただし、最小クォーラムサイズを設定すると、最小しきい値を満たしていない更新を拒否するようにクラスタを設定できます。 +
これにより、一貫性が向上し、予期せずにノード (クラスタ内の Mule Runtime) が失われた場合にクラスタを保護できます。

通常の状況では、クラスタ内のノードが停止しても、データを保存するのに十分なメモリがありますが、使用可能なノードが少なくなるため要求の処理に使用できるスレッド数が減少し、クラスタ内のパーティションスレッドがすぐに不足する可能性があります。そのため、次のことが発生する場合があります。

* クライアントの要求を処理するスレッドがなくなり、クライアントが置き去りになる
* 応答できない要求が多すぎて残りのクラスタメンバーで処理しきれなくなり、停止していると想定されてクラスタから除外されます。

メンバーが失われた場合にクラスタの残りのメンバーを保護するには、ノードの同時更新を停止する最小クォーラムサイズを設定します。これにより、クラスタ内のアクティブなノードの数が設定値を下回ったとき、+QuorumException+ がスローされます。

[CAUTION]
====
*QuorumExceptions をキャッチしてください*

クラスタのクォーラムサイズを設定する場合、スローされた例外をキャッチして何らかの決定 (メールの送信、プロセスの停止、ログ記録、戦略の再試行など) を行う必要があります。
====

クォーラムを有効にするには、+mule.cluster.quorumsize+ プロパティをクラスタ設定ファイル +{MULE_HOME}/.mule/mule-cluster.properties+ に配置して、稼働状態を維持するためのクラスタの最小ノード数を定義する必要があります。

[NOTE]
--
クォーラム機能は、オブジェクトストアを使用するコンポーネントでのみ有効です。
--

=== オブジェクトストアの永続性

すべてのクラスタノードからアクセスできる中央システムに JDBC データを永続的に保存できます。

[TIP]
--
サポートされているリレーショナルデータベース管理システムのリストについては、Mule のxref:hardware-and-software-requirements.adoc#mule-database-servers[「ハードウェアおよびソフトウェアの要件」]を参照してください。
--

オブジェクトストアの永続性を有効にするには、データベースを作成し、+{MULE_HOME}/.mule/mule-cluster.properties+ ファイルでその設定値を定義する必要があります。

. *mule.cluster.jdbcstoreurl*: データベースに接続するための JDBC URL
. *mule.cluster.jdbcstoreusername*: データベースのユーザ名
. *mule.cluster.jdbcstorepassword*: データベースのユーザパスワード
. *mule.cluster.jdbcstoredriver*: JDBC ドライバのクラス名
. *mule.cluster.jdbcstorequerystrategy*: SQL 言語

この機能により、保持するオブジェクトストアごとにテーブルが作成されるため、データベースのテーブルは自動的に作成されます。 +
オブジェクトストアごとに 2 つのテーブルが作成されます。

* データを保存するテーブル
* パーティションを保存するテーブル

==== オブジェクトストアデータベースの推奨事項

* JDBC ストアでのみ使用される専用データベース/スキーマを作成することをお勧めします。
* データベースのユーザ名は、次の権限が必要です。
** データベースのオブジェクトを作成する権限 (テーブルの DDL CREATE、DROP)。
** 作成されるオブジェクトに対する DML 権限 (INSERT、UPDATE、DELETE、SELECT)
* データストレージは、すべてのノードからアクセスできる中央 DB でホストする必要があることを常に念頭に置いてください。クラスタごとに複数のデータベースを使用しないでください。 +
これらの値の設定方法についての詳細は、「<<persistency-config,cluster configuration reference for persistency (永続性のクラスタ設定リファレンス)>>」を参照してください。
* 永続的なオブジェクトストアは、`ComboPooledDataSource` Java クラスに基づいたデータベース接続プールを使用します。Mule Runtime Engine は、接続プールの動作の明示的な値を設定しません。標準設定では、各プロパティのデフォルト値を使用します。 +
たとえば、`maxIdleTime` のデフォルト値は 0 です。これは、アイドル接続の期限が切れず、プールから削除されないことを意味します。アイドル接続は、アイドル状態でデータベースに接続されたままになります。 +
接続プールの動作を設定するには、次のいずれかのオプションを使用して目的のパラメータ値をランタイムに渡します。
** Mule の起動時にコマンドラインで複数のパラメータを渡す。
+
[source,console]
----
$ $MULE_HOME/bin/mule start \
-M-Dc3p0.maxIdleTime=<value> \
-M-Dc3p0.maxIdleTimeExcessConnections=<value>
----
+
`<value>` を目的の値 (ミリ秒) に置き換えます。

** `$MULE_HOME/conf/wrapper.conf` ファイルに複数行を追加する。
+
----
wrapper.java.additional.<n>=-Dc3p0.maxIdleTime=<value>
wrapper.java.additional.<n>=-Dc3p0.maxIdleTimeExcessConnections=<value>
----
+
`<n>` を `wrapper.conf` ファイルの次に大きい順次値に置き換えます。
+
[NOTE]
`ComboPooledDataSource` Java クラスのプール設定についての詳細は、http://www.mchange.com/projects/c3p0/#configuration[この記事]を参照してください。

=== 監視

http://www.oracle.com/technetwork/java/javase/tech/javamanagement-140525.html[JMX テクノロジ]を使用して、クラスタメンバーでスローされるイベントを監視できます。

JMX 監視オプションは、デフォルトで無効になっています。有効にするには、+mule.cluster.jmxenabled+ プロパティを +{MULE_HOME}/.mule/mule-cluster.properties+ 設定ファイルに追加します。

JMX を有効にすると、パフォーマンスのオーバーヘッドが発生する可能性があります (基盤となる構造で各ノードの統計を取得するためのリスナが追加される場合)。


=== メンバーシップリスナ

メンバーシップリスナを使用すると、次のイベントが発生するたびに通知を取得できます。

. 新しいメンバーがクラスタに追加される
. 既存のメンバーがクラスタから離脱する

これらのいずれかのイベントがトリガされると、メンバーシップリスナは、参加または離脱したメンバーのアドレスを出力します。

== クラスタ設定パラメータ

次の表に、`mule-cluster.properties` ファイルのパラメータを示します。

[%header%autowidth.spread]
|===
|プロパティ名 |説明
|`mule.clusterId` |*必須。*クラスタの一意の識別子。任意の英数字文字列になります。
|`mule.clusterNodeId` |*必須。*クラスタ内のノードの一意の ID。1 ～クラスタ内のノード数の間の整数になります。
|`mule.cluster.networkinterfaces` a|
Hazelcast で使用されるインターフェースのカンマ区切りリスト。以下のようにワイルドカードがサポートされています。

----
192.168.1.*,192.168.100.25
----

|`mule.cluster.nodes` a|
クラスタに属するノード。`<host:port>` の形式になります (例: `172.16.9.24:9000`)。1 つの IP アドレスのみを指定すると、サーバがクラスタに参加できるようになります。

ポート番号は省略可能です。設定しない場合は、デフォルトは 5701 になります。複数のホストを含めるには、カンマ区切りリストを作成します。

このオプションでは、指定した固定 IP アドレスでクラスタを設定します。クラスタノードの検出にマルチキャストを使用しない場合、このオプションを使用します。このオプションを使用する場合、`mule.cluster.multicastenabled` を `false` に設定します。そのように設定しないと、クラスタを開始するときに例外がスローされます。(この表の次の項目を参照)。 +

例:

ポート 9000 をリスンする 2 つのノード:

----
172.16.9.24:9000,172.16.9.51:9000
----

ポート 5701 をリスンする 2 つのノード:

----
192.168.1.19,192.168.1.20
----

|`mule.cluster.quorumsize` | 稼働状態を維持するためにクラスタ内に必要なマシンの最小数を定義できます。
|`mule.cluster.multicastenabled` |*(Boolean (ブール))* マルチキャストを有効/無効にします。クラスタノードの検出に固定 IP アドレスを使用する場合、`false` に設定します (上記の `mule.cluster.nodes` オプションを参照)。 +
`true` に設定する場合、`mule.cluster.nodes` で IP アドレスを設定しないでください。
|`mule.cluster.multicastgroup` |使用するマルチキャストグループ IP アドレス。
|`mule.cluster.multicastport` |使用するマルチキャストポート番号。
| [[persistency-config]] `mule.cluster.jdbcstoreurl` | *永続データを保存する場合のみ必須*。 +
データベースに接続するための JDBC URL
|`mule.cluster.jdbcstoreusername` |*永続データを保存する場合のみ必須*。 +
データベースのユーザ名
|`mule.cluster.jdbcstorepassword` |*永続データを保存する場合のみ必須*。 +
データベースのユーザパスワード
|`mule.cluster.jdbcstoredriver` |*永続データを保存する場合のみ必須*。 +
JDBC ドライバのクラス名
|`mule.cluster.jdbcstorequerystrategy` |*永続データを保存する場合のみ必須*。 +
保存されているオブジェクトデータにアクセスするための SQL 言語。 +
このプロパティは、3 つの異なる値 (`mssql`、`mysql`、`postgresql`) を取ります。
|`mule.cluster.jmxenabled`| *(Boolean (ブール))* 監視を有効/無効にします。
| `mule.cluster.listenersenabled` | *(Boolean (ブール))* メンバーシップリスナを有効/無効にします。クラスタメンバーが参加または離脱したときにノードに通知するには、`true` に設定します。
|===
