= 複数のペイロードのマージ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Studio, Anypoint, 変換, トランスフォーマ, 形式, 集約, filter, json, メタデータ, DataWeave, data weave, datamapper, dwl, dfl, dw, 出力構造, 入力構造, map, マッピング, contains, as

この DataWeave の例では、ペイロードのコレクションが含まれる入力に対処します。最初のペイロードは本ごとの価格をリストし、2 番目のペイロードは本ごとの著者をリストします。各本は一意の `bookId` キーで識別できます。この変換では、キーを照合して両方のペイロードを 1 つにマージします。1 つの本に複数の著者がいる場合もあります。


[NOTE]
これは、配列で構成される 1 つのペイロードを入力として設定することとは異なります。ここでは、1 つの Mule イベントオブジェクト内に複数の個別のペイロード要素があります。この種のデータ構造は、scatter-gather コンポーネントなどで生成されます。

次の関数を使用します。

* `map`。最初のペイロード (`payload[0]`) の要素を調べます。2 番目の `map` 関数は、要素ごとに検索条件に一致する 2 番目のペイロード (`payload[1]`) の要素を調べます。
* `using`。メイン `map` 関数のスコープ内の短い別名を定義します。
* `filter`。2 番目の `map` 関数のスコープを、現在最初の `map` 関数で処理されているオブジェクトと同じ `bookId` を共有するオブジェクトに制限します。このようにして、それぞれの関連する著者のみが出力にリストされます。



.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---

payload[0]  map (bookListing) -> using (id = bookListing.bookId) {
	bookId:	id,
    title:  bookListing.title,
	price: 	bookListing.price as Number,
	(payload[1] filter ($.*bookId contains id)  map (bookAuthor) -> {
		author:bookAuthor.author
   })
}
----

////
This is not the same as the original example. Like that it's not too different from the "group by" example, except that it does things in a less efficient way.

The whole point of this example is that the input is in separate objects.


.Input
[source,json,linenums]
----
{
  "Book Price by ID" : [
    {
      "bookId": 101,
      "title": "Some Book",
      "price" : 7.15
    },
    {
      "bookId": 102,
      "title": "Another Book",
      "price" : 40.75
    }],
  "Book Author by ID"  : [
    {
      "bookId": 101,
      "author"  : "Some Body"
    },
    {
      "bookId": 102,
      "author"  : "Some Body Else"
    }]
}
----
////

.コレクションの入力 1 - Payload[0]
[source,json,linenums]
----
[
  { "bookId":"101",
    "title":"world history",
    "price":"19.99"
  },
  {
    "bookId":"202",
    "title":"the great outdoors",
    "price":"15.99"
  }
]
----

.コレクションの入力 2 - Payload[1]
[source,json,linenums]
----
[
  {
    "bookId":"101",
    "author":"john doe"
  },
  {
    "bookId":"202",
    "author":"jane doe"
  }
]
----




.出力
[source,json,linenums]
----
[
  {
    "bookId": "101",
    "title": "world history",
    "year": "2017",
    "isbn": "11111",
    "price": "19.99",
    "author": "john doe"
  },
  {
    "bookId": "202",
    "title": "the great outdoors",
    "year": "2016",
    "isbn": "22222",
    "price": "15.99",
    "author": "jane doe"
  }
]
----





////
.Output
[source,json,linenums]
----
[
  {
    "bookId": 101,
    "title": "Some Book",
    "price": 7.15,
    "author": "Some Body"
  },
  {
    "bookId": 102,
    "title": "Another Book",
    "price": 40.75,
    "author": "Some Body Else"
  }
]
----
////
////
Note that the *sample data* section of the Transform component does not allow you to provide it a collection of multiple payloads as a sample. The only way to test this example is running it.
////

== 関連する例

* xref:dataweave-cookbook-extract-data.adoc[データの抽出]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[複数の入力の参照]

* xref:dataweave-cookbook-zip-arrays-together.adoc[複数の配列要素のグループ化]

== 関連情報

* xref:dataweave-selectors.adoc[DataWeave セレクタ]

* xref:dataweave-cookbook.adoc[DataWeave の解説書]
