= Studio 外でのデバッグ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: デバッグ, デバッグ


Anypoint Studio で Mule アプリケーションのトラブルシューティングを行うには、xref:studio::visual-debugger-concept.adoc[Studio ビジュアルデバッガ]を使用できます。これを使用すると、ブレークポイントを設定して実行を停止し、イベントを確認できます。

Studio 外で Mule アプリケーションを作成する場合は、MUnit を使用してアプリケーションをテストするか、リモートデバッグをアクティブ化することができます。

== MUnit を使用したアプリケーションのテスト

MUnit とは Mule アプリケーションテストフレームワークであり、インテグレーションおよび API の自動テストをビルドできます。完全なインテグレーションおよびユニットテスト機能が提供され、継続的なデプロイメント環境とのインテグレーション用に Maven および Surefire と完全に統合されています。

詳細は MUnit のドキュメントを参照してください。

== リモートデバッグのアクティブ化

次の Linux の例のように、*-debug* オプションを使用して Mule を開始し、リモートデバッグをアクティブ化することができます。

----
$MULE_HOME/bin/mule -debug
----

このオプションを使用すると、Mule は通常どおりに開始され、次のメッセージがコンソールに記録されます。

----
Listening for transport dt_socket at address: 5005
----

これで Mule をポート 5005 でリモードでデバッグできます。以下の手順に従って。Mule をデバッグします。

. Eclipse にアクセスし、*[Run (実行)] > [Debug Configurations (デバッグ設定)]* メニューを選択します。ここで、ポート 5005 を使用する *[Remote Java Application (リモート Java アプリケーション)]* 設定を作成します。

. 設定パネルの 2 番目のタブで、Mule ローカルインスタンスのソースコードを外部アーカイブとして追加します。

. 設定画面の右下隅にある *[Debug (デバッグ)]* ボタンをクリックします。ローカルの Mule インスタンスがその起動シーケンスを再開し、これでアプリケーションをステップごとにデバッグできます。

5005 以外のポートを使用する場合は、Mule のデバッグ手順を実行する前に Mule 起動スクリプト内の JPDA_OPTS プロパティファイルを変更します。
