= orderBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[orderby1]]
== orderBy&#40;O, &#40;value: V, key: K&#41; &#45;&#62; R&#41;: O

入力の要素を、その入力の選択された要素で動作する条件を使用して並び替えます。


このバージョンの `orderBy` は、入力としてオブジェクトを使用します。その他のバージョンは、入力配列で動作するか、null 値を処理します。

インデックスは匿名パラメータ `&#36;&#36;`、値は `&#36;` で参照できます。

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `object` | 並び替えるオブジェクト。
| `criteria` | 関数の結果は、オブジェクトを並び替える条件として使用されます。
|===

=== 例

次の例では、入力配列内の各オブジェクトの値をアルファベット順に並べます。`orderBy($.letter)` は `orderBy($[0])` と同じ結果になります。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ orderByLetter: [{ letter: "e" }, { letter: "d" }] } orderBy($.letter)
----

==== 出力

[source,JSON,linenums]
----
{ "orderByLetter": [ { "letter": "e" }, { "letter": "d" } ] }
----

=== 例

`orderBy` 関数には、昇順ではなく降順で並び替えるオプションはありません。この場合は、たとえば `-` を使用して、結果の配列の順序を単に反転することができます。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
orderDescending: ([3,8,1] orderBy -$)
----

==== 出力

[source,JSON,linenums]
----
{ "orderDescending": [8,3,1] }
----


[[orderby2]]
== orderBy&#40;Array<T&#62;, &#40;item: T, index: Number&#41; &#45;&#62; R&#41;: Array<T&#62;

指定された条件を使用して配列を並び替えます。


=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `array` | 並び替える配列。
| `criteria` | 関数の結果は、リストを並び替える条件として使用されます。単純な値 (文字列、数値など) を返す必要があります。
|===

=== 例

次の例では、数値に基づいて数値の配列を並び替えます。

==== 取得元

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[3,2,3] orderBy $
----

==== 出力

[source,JSON,linenums]
----
[ 2, 3, 3 ]
----

=== 例

次の例では、age (年齢) に基づいて人の配列を並び替えます。

==== 取得元

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[{name: "Santiago", age: 42},{name: "Leandro", age: 29}, {name: "Mariano", age: 35}] orderBy (person) -> person.age
----

==== 出力

[source,JSON,linenums]
----
[
  {
    name: "Leandro",
    age: 29
  },
  {
    name: "Mariano",
    age: 35
  },
  {
    name: "Santiago",
    age: 42
  }
]
----


[[orderby3]]
== orderBy&#40;Null, &#40;item: Nothing, index: Nothing&#41; &#45;&#62; Null&#41;: Null

*orderBy* を null 値に使用できるようにするヘルパー関数。

