= sizeOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[sizeof1]]
== sizeOf&#40;Array<Any&#62;&#41;: Number

配列内の要素数を返します。配列が空の場合は `0` を返します。


このバージョンの `sizeOf` は、配列、または配列の配列を入力として使用します。
その他のバージョンは、オブジェクト、文字列、またはバイナリ値の配列で動作します。

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `array` | 入力配列。配列の要素には、サポートされる任意のデータ型を使用できます。
|===

=== 例

次の例では、入力配列内の要素数をカウントします。`3` を返します。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf([ "a", "b", "c"])
----

==== 出力

[source,JSON,linenums]
----
3
----

=== 例

次の例では、入力配列内の要素数を返します。

==== 取得元
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  "arraySizes": {
     size3: sizeOf([1,2,3]),
     size2: sizeOf([[1,2,3],[4]]),
     size0: sizeOf([])
   }
}
----

==== 出力
[source,JSON,linenums]
----
{
   "arraySizes": {
     "size3": 3,
     "size2": 2,
     "size0": 0
   }
}
----


[[sizeof2]]
== sizeOf&#40;Object&#41;: Number

オブジェクト内のキー-値ペア数を返します。


この関数はオブジェクトの配列を受け入れます。入力オブジェクトが空の場合は `0` を返します。

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `object` | 1 つ以上のキー-値ペアを含む入力オブジェクト。
|===

=== 例

次の例では、入力オブジェクト内のキー-値ペア数をカウントし、`2` を返します。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf({a: 1, b: 2})
----

==== 出力

[source,JSON,linenums]
----
2
----

=== 例

次の例では、オブジェクト内のキー-値ペア数をカウントします。

==== 取得元
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
   objectSizes : {
     sizeIs2: sizeOf({a:1,b:2}),
     sizeIs0: sizeOf({})
   }
}
----

==== 出力
[source,JSON,linenums]
----
{
  "objectSize": {
    "sizeIs2": 2,
    "sizeIs0": 0
  }
}
----


[[sizeof3]]
== sizeOf&#40;Binary&#41;: Number

バイナリ値の配列内の要素数を返します。


=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `binary` | バイナリ値の入力配列。
|===

=== 例

次の例では、バイナリ値の配列のサイズを返します。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf(["\u0000" as Binary, "\u0001" as Binary, "\u0002" as Binary])
----

==== 出力

[source,JSON,linenums]
----
3
----


[[sizeof4]]
== sizeOf&#40;String&#41;: Number

文字列内の文字数 (空白を含む) を返します。


文字列が空の場合は `0` を返します。

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前)   | 説明
| `text` | 入力テキスト。
|===

=== 例

次の例では、入力文字列 `"abc"` 内の文字数を返します。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf("abc")
----

==== 出力

[source,JSON,linenums]
----
3
----

=== 例

次の例では、入力配列内の文字数を返します。文字列 `"my string"` 内の空白スペースはカウントされます。また、`sizeOf("123" as Number)` では、`123` が数値に強制変換されて文字列ではなくなるため、`1` が返されます。

==== 取得元

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  sizeOfSting2 : sizeOf("my string"),
  sizeOfEmptyString: sizeOf(""),
  sizeOfNumber : sizeOf("123" as Number)
}
----

==== 出力

[source,JSON,linenums]
----
{
  "sizeOfSting2": 9,
  "sizeOfEmptyString": 0,
  "sizeOfNumber": 1
}
----

