== DataFormat 型 (dw::extension::DataFormat)

[%headers, cols="1,3,6"]
|===
| 型 | 定義 | 説明

| DataFormat
| `type DataFormat = { binaryFormat?: Boolean, defaultCharset?: String,
fileExtensions?: Array<String&#62;,
acceptedMimeTypes: Array<MimeType&#62;,
reader: &#40;content: Binary,
charset: String,
settings: ReaderSettings&#41; &#45;&#62; Any,
writer: &#40;value: Any,
settings: WriterSettings&#41; &#45;&#62; Binary }`
a|

* `binaryFormat?: Boolean`: これがテキストではなくバイナリ表現のデータ形式の場合は True、存在しないは false です。
* `defaultCharset?: String`: この形式のデフォルトの文字セット (ある場合)。
* `fileExtensions?: Array<String&#62;`: このデータ形式に割り当てる必要がある「.」付きのファイル拡張子 &#40;「.json」、「.xml」など&#41; のリストを返します。
* `acceptedMimeTypes: Array<MimeType&#62;`: 受け入れられる MimeType のリスト。
* `reader: (content: Binary, charset: String, settings: ReaderSettings) -> Any`:
この関数は、未加工のコンテンツを読み取って DataWeave 正規モデルに変換します。
* `writer: (value:Any, settings:WriterSettings) -> Binary`: この関数は、DataWeave 正規モデルをバイナリコンテンツに書き込みます。


| EmptySettings
| `type EmptySettings = Object`
|


| EncodingSettings
| `type EncodingSettings = { encoding?: String }`
a|

* `encoding?: String`: このライターで使用するエンコード。

| MimeType
| `type MimeType = String`
|


| Settings
| `type Settings = Object`
|

|===
