= ファイル
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[file1]]
== file&#40;{&#124; name: String, path: String, mime?: String, fileName?: String &#124;}&#41;

ソースファイルから `MultipartPart` データ構造を作成します。


このバージョンの `file` 関数は、パラメータ名をキーとして使用するオブジェクトの配列として引数を受け入れます。例: 

[source,txt,linenums]
----
Multipart::file({ name: "myFile", path: "myClients.json", mime: "application/json", fileName: "partMyClients.json"})
----

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前) | 説明
| `opts` a| 以下を指定するオブジェクトの配列。

* `name` (必須): パートの `Content-Disposition` ヘッダーの一意の名前。
* `path` (必須): Mule アプリケーションの `src/main/resources` プロジェクトパスを基準とする相対パス。
* `mime` (文字列の場合は省略可能): パート内のコンテンツに適用する MIME タイプ (例: `application/json`)。この設定を使用して入力の MIME タイプを変換することは _できません_ 。
* `fileName` (省略可能): パートの `Content-Disposition` ヘッダー内の `filename` パラメータの値。指定されていない場合、デフォルトの文字列 `"filename"` に設定されます。この値は入力ファイル名に一致する必要はありません。
|===

=== 例

次の例では、ファイルの内容を `MultipartPart` から `Multipart` データ構造に挿入します。`form` 関数を使用して `Multipart` を作成し、`file` を使用して外部ファイル `myClients.json` の JSON コンテンツを含む `myClient` という名前のパートを作成します。また、`filename` パラメータの値として `partMyClients.json` を指定します。

==== 取得元

[source,DataWeave,linenums]
----
%dw 2.0
import dw::module::Multipart
output multipart/form-data
var myClients = "myClients.json"
var myArgs = { name: "myFile", path: "myClients.json", mime: "application/json", * fileName: "partMyClients.json"}
---
Multipart::form([
  Multipart::file(myArgs)
])
----

==== 入力

次のコンテンツを含む、`src/main/resources` に配置されている `myClients.json` という名前のファイル。

[source,JSON,linenums]
----
clients: {
  client: {
    id: 1,
     name: "Mariano"
   },
   client: {
     id: 2,
     name: "Shoki"
  }
}
----

==== 出力

[source,json,linenums]
----
------=_Part_1586_1887987980.1542569342438
Content-Type: application/json
Content-Disposition: form-data; name="myFile"; filename="partMyClients.json"

{
   clients: {
     client: {
       id: 1,
       name: "Mariano"
     },
     client: {
       id: 2,
       name: "Shoki"
     }
   }
}
------=_Part_1586_1887987980.1542569342438--
----


[[file2]]
== file&#40;String, String, String, String&#41;

ソースファイルから `MultipartPart` データ構造を作成します。


このバージョンの `file` 関数は、次のようにカンマ区切りリストで引数を受け入れます。

[source,txt,linenums]
----
Multipart::field("myFile", myClients, 'application/json', "partMyClients.json")
----

=== パラメータ

[%header, cols="1,3"]
|===
| Name (名前) | 説明
| `opts` a| 以下を指定するオブジェクトの配列。

* `name` (必須): パートの `Content-Disposition` ヘッダーの一意の名前。
* `path` (必須): Mule アプリケーションの `src/main/resources` プロジェクトパスを基準とする相対パス。
* `mime` (文字列の場合は省略可能): パート内のコンテンツに適用する MIME タイプ (例: `application/json`)。この設定を使用して入力の MIME タイプを変換することは _できません_ 。
* `fileName` (省略可能): パートの `Content-Disposition` ヘッダー内の `filename` パラメータの値。指定されていない場合、デフォルトの文字列 `"filename"` に設定されます。この値は入力ファイル名に一致する必要はありません。
|===

=== 例

次の例では、ファイルの内容を `MultipartPart` から `Multipart` データ構造に挿入します。`form` 関数を使用して `Multipart` 型を作成し、`file` を使用して外部ファイル `myClients.json` の JSON コンテンツを含む `myClient` という名前のパートを作成します。また、`filename` パラメータの値として `partMyClients.json` を指定します。

==== 取得元

[source,DataWeave,linenums]
----
%dw 2.0
import dw::module::Multipart
var myClients = "myClients.json"
output multipart/form-data
---
Multipart::form([
 Multipart::file("myFile", myClients, 'application/json', "partMyClients.json")
])
----

==== 入力

次のコンテンツを含む、`src/main/resources` に配置されている `myClients.json` という名前のファイル。

[source,JSON,linenums]
----
clients: {
    client: {
      id: 1,
      name: "Mariano"
    },
    client: {
      id: 2,
      name: "Shoki"
    }
  }
----

==== 出力

[source,json,linenums]
----
------=_Part_1586_1887987980.1542569342438
Content-Type: application/json
Content-Disposition: form-data; name="myFile"; filename="partMyClients.json"

{
   clients: {
     client: {
       id: 1,
       name: "Mariano"
     },
     client: {
       id: 2,
       name: "Shoki"
     }
   }
}
------=_Part_1586_1887987980.1542569342438--
----

