= ハードウェアとソフトウェアに関する Mule 要件
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Mule, 要件, jdk, インストール

Mule をオンプレミスでインストールして実行する場合は、インストール前にハードウェアとソフトウェアの最小要件を確認します。

== 最小ハードウェア要件

* 2 GHz の CPU または仮想環境の仮想 CPU
* 1 GB の RAM。遅延要件に合わせて、またはアプリケーションで大きな同時メッセージや多数の同時メッセージを処理する場合はそれをサポートするように、RAM を追加します。
* 4 GB のストレージ

== 最小ソフトウェア要件

Mule をインストールする前に、サポートされているバージョンの Java とサポートされているオペレーティングシステムを使用していることを確認します。

アプリケーションサーバを使用する場合や、データストアにアクセスする必要がある場合は、サポートされているアプリケーションやデータベースを使用していることを確認します。

=== サポートされている Java バージョン

* Oracle JDK 1.8.0 (JDK 1.8.0_161 推奨)
* IBM JDK 1.8
* OpenJDK 8 (JDK 1.8.0_162 推奨)

=== サポートされているオペレーティングシステム

* MacOS 10.11.4
* HP-UX 11i V3
* AIX 7.2
* Windows Server 2016 (推奨)、Windows 2012 R2 Server、Windows 10 (推奨)、Windows 8.1
* Solaris 11.3
* RHEL 7
* Ubuntu Server 15.04 または 16.04、またはその他の Linux ディストリビューション (サポートされている JDK と Linux カーネル 3.13 を実行していること)

=== アプリケーションサーバ

Mule はスタンドアロンサーバとして実行されるため、アプリケーションサーバは必須ではありません。ただし、Mule は、サポートされている次のアプリケーションサーバのいずれかの下で実行できます。

* Tomcat 7 および 8
* WebLogic 12c
* WebSphere 8
* WildFly 8 または 9
* Jetty 8 または 9

=== 追加要件

* Microsoft Dynamics GP コネクタを使用する場合は、JRE または JDK をインストールした後に Java Cryptography Extension (JCE) 8 をインストールします。
* データストアにアクセスする必要があれば、データベースが必要です。Mule は、サポートされている次のデータベースにアクセスできます。
+
** Mule Oracle 11g
** Oracle 12c
** MySQL 5.5+
** IBM DB2 10
** PostgreSQL 9
** Derby 10
** Microsoft SQL Server 2014

== 関連情報

Mule やその他の製品での使用がテストされている最新のハードウェアおよびソフトウェアバージョンを確認するには、その製品のxref:release-notes::index.adoc[リリースノート]を参照してください。
