= アプリケーションのホットデプロイメント
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: ランタイム, デプロイ, ホットデプロイメント, アプリケーション, アプリケーション

設定ファイルとカスタムクラスを変更し、Mule を再起動せずにそれらを再読み込みします。

== デプロイメントの概要

アプリケーション「foo」のデプロイの概要を次に示します。

* `$MULE_HOME/apps/foo` の下にディレクトリを作成します。
* パッケージ化したアプリケーション (例: `foo.jar`) を `$MULE_HOME/apps` に配置します。
* カスタムクラスがある場合は、JAR に圧縮して `$MULE_HOME/apps/foo/META-INF/mule-src/foo/src/main/java/` の下に配置します。
* `mule -M-Dmule.deploy.applications=foo` と入力して、アプリケーションを開始します。

アプリケーションの設定ファイルは監視されます。つまり、クラスの変更を追加する必要がある場合や、設定の変更がある場合、Mule 設定ファイルのいずれかを保存または変更すると、Mule はアプリケーションのホット再読み込みを実行します。

== ホットデプロイメントのしくみ

Mule は、更新された設定ファイルが `$MULE_HOME/apps` ディレクトリ下にないかどうかを 3 秒ごとに確認し、更新された設定ファイルを見つけると、設定ファイルと JAR をそのアプリケーションの `java` ソースディレクトリに再読み込みします。アプリケーションを再読み込みするには、以下の操作を実行できます。

* 該当のアプリケーションのアンカーファイルを変更します。
* xref:intro-packaging#app_descriptor[`mule-artifact.json`] ファイル内で宣言されている Mule 設定ファイルのいずれかを変更または更新します。

たとえば、カスタムクラスの 1 つを変更する場合、そのカスタムクラスに変更を加え、更新したクラスを Java ディレクトリにコピーした後、アンカーファイルを変更します。

== 関連情報
* xref:application-deployment.adoc[アプリケーションデプロイメント]
