= Mule 4 の概要: コネクタ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

システムに接続する場合、Mule 3 にはトランスポートとコネクタという 2 つの手段がありました。トランスポートは、インバウンドおよびアウトバウンドエンドポイントという概念を用いてデータを送信します。コネクタは、操作という概念を用いてシステムを呼び出します (`<http:request>`、`<db:select>` など)。

MuleSoft は、Mule 3 で一部のトランスポートを新しい HTTP Connector や データベースコネクタに切り替え始めました。Mule 4 でこの変更が完了し、すべての接続性をコネクタとして構築するアプローチが完全に標準化されています。この変更により、コネクタの一貫性と使いやすさが向上し、コネクタの機能が強化されます。

== コアコネクタやコアモジュールの独立したリリースサイクル

もう一つの大きな違いは、コネクタの配布およびリリース方法です。Mule 3 では、Mule Runtime の配布に多数のコネクタやトランスポート (File、FTP、SFTP、Database、JMS、XML、Validations など) が付属していました。こうしたコネクタの修正や機能拡張は、Mule Runtime の次回のリリースまで待たなければなりませんでした。その一方で、他のコネクタは (Salesforce、Workday、ServiceNow、SAP など、主として SaaS コネクタ)、独立して配布やリリースされていました。

Mule 4 では、最新のモデルを標準化しています。Mule 4 の配布にはコネクタやモジュールが 1 つも付属していません。代わりに、各アプリケーションに必要なモジュールが含まれています。こうしたアプローチには次のメリットがあります。

* どのコネクタにも独自のリリースサイクルがあるため、コアモジュール/コアコネクタでの迅速なイノベーションが可能になる。Mule Runtime の次のリリースまで待たなくても、新機能やバグ修正が手に入ります。
* 異なるアプリケーションで、同じモジュールの異なるバージョンを使用できる。このため、新しいリリースを簡単に採用でき、アップグレードが不要なアプリケーションを完全退行させる必要がありません。
* 一貫したアプローチが可能になる。
