= Mule 4 コンポーネント変更リファレンス
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Studio, サーバ, コンポーネント, コネクタ, 要素, パレット, グローバル要素, 設定要素

== Mule コアの変更

次の表では、Mule 3.x のコンポーネントおよび式と Mule 4.0 での代替機能を示しています。一部の代替機能はまだ開発中であり、その旨を示しています。

[%header,cols="30,70"]
|===
Mule 3.x のコンポーネント|Mule 4.0 の代替法|
すべての router |代わりに scatter gather を使用するか、異なる対象属性で操作を 1 つずつ実行してから DW を使用して結果をマージします。|
async[‘processingStrategy’]|非ブロック実行エンジンには async processing strategy (非同期処理戦略) が不要になりました。非同期の動作が必要な場合は、“async” スコープを使用してすべてのコンポーネントをラップします。|
asynchronous-processing-strategy|非ブロック実行エンジンには async processing strategy (非同期処理戦略) が不要になりました。非同期の動作が必要な場合は、“async” スコープを使用してすべてのコンポーネントをラップします。|
bridge|排除されました。フローを使用します。|
catch-exception-strategy|on-error-continue 戦略と一緒に error-handler を使用します。|
choice-exception-strategy|エラー種別選択または when 属性を使用して内部で異なる戦略と一緒に error-handler を使用します。|
combine-collections-transformer|簡略化されたメッセージモデルでは不要になりました。MuleMessageCollections は Mule メッセージの配列に置き換わります。これは、DataWeave や foreach などの任意の Mule コンポーネントを使用してマージまたは反復できます。|
コンポーネント|Java モジュールを使用します (開発中)。|
composite-source|各ソースあたり 1 つのフローを作成し、共通機能の flow-ref を使用して非公開フローを呼び出します。|
configuration[‘defaultExceptionStrategy-ref’]|defaultErrorHandler-ref の新しい名前。|
configuration[‘flowEndingWithOneWayEndpointReturnsNull’]|新しい実行エンジンでは不要になりました。|
configuration[‘useExtendedTransformations’]|排除されました。|
configuration[enricherPropagatesSessionVariableChanges]|排除されました。|
copy-attachments|Transform コンポーネントおよび DataWeave を使用します。|
copy-properties|Transform コンポーネントおよび DataWeave を使用します。|
custom-agent|排除されました。|
custom-aggregator|custom-aggregator を不要にするために開発中の代替機能。|
custom-connector|SDK を使用してカスタムコネクタを作成します。|
custom-exception-strategy|不要になりました。error-handler を使用します。|
custom-lifecycle-adapter-factory|代替機能はありません。|
custom-object-store|オブジェクトストアモジュール拡張機能を使用してカスタムストアを作成します。|
custom-processor|DataWeave、スクリプティングコンポーネント、Mule SDK (開発中)、または Java モジュール (開発中) を使用します。|
custom-queue-store|新しい VM コネクタ (開発中) を使用します。|
custom-router-resolver|排除されました。|
custom-router|排除されました。|
custom-service|フローを使用します。|
custom-source|Mule SDK (開発中) を使用して新しいイベントソースを記述します。|
custom-splitter|custom-splitter を不要にするために開発中の代替機能。|
custom-transaction-manager|代替機能を開発中。|
custom-transaction|排除されました。|
default-exception-strategy|on-error-propagate 戦略を使用する error-handler を使用します。|
default-in-memory-queue-store|新しい VM コネクタ (開発中) を使用します。|
default-persistent-queue-store|新しい VM コネクタ (開発中) を使用します。|
default-service-exception-strategy|on-error-propagate 戦略を使用する error-handler を使用します。|
endpoint|コネクタを使用します。|
exception-strategy|error-handler を使用します。|
expression-component|DataWeave、スクリプティングコンポーネント、Mule SDK (開発中)、または Java モジュール (開発中) を使用します。|
file-queue-store|新しい VM コネクタ (開発中) を使用します。|
flow[‘processingStrategy’]|排除されました。非ブロック実行エンジンを使用すれば、ユーザはこれを調整する必要がありません。|
idempotent-message-filter|代替機能を開発中。|
idempotent-redelivery-policy|redelivery-policy の新しい名前。|
idempotent-secure-hash-message-filter|ペイロードにハッシュを適用する関数を idempotent-redelivery-message の id 式属性値として使用できます。|
in-memory-store|オブジェクトストアモジュール拡張機能を使用してカスタムストアを作成します。|
inbound-endpoint|コネクタを使用します。|
include-entry-point|Java モジュールを使用します (開発中)。|
interceptor-stack|代替機能を開発中。|
invoke|Java モジュールを使用します (開発中)。|
jndi-transaction-manager|代替機能を開発中。|
jrun-transaction-mamanger|代替機能を開発中。|
legacy-abstract-exception-strategy|新しいエラーハンドラを使用します。|
managed-store|オブジェクトストアモジュール拡張機能を使用してカスタムストアを作成します。|
message-properties-transformer|Transform コンポーネントおよび DataWeave を使用します。|
model|排除されました。代わりにフローを使用します。 |
mule[‘version’]
outbound-endpoint|要素はコア名前空間から新しいトランスポート名前空間に移動されました。|
parse-template
poll -> watermark|object-store モジュールを使用して透かし値を手動で設定します。|
poll|スケジューラソースに置き換えられました。|
pooling-profile[‘disabled’]|新しい属性です。|
processor|DataWeave、スクリプティングコンポーネント、Mule SDK (開発中)、または Java モジュール (開発中) を使用します。|
prototype-object|Java モジュールまたは Spring モジュールを使用します。|
queue-profile|排除されました。|
queue-store|排除されました。|
recipient-list|排除されました。|
reconnect-custom-notifier|排除されました。|
reconnect-custom-notifier|排除されました。|
reconnect-custom-strategy|排除されました。|
reconnect-custom-strategy|排除されました。|
reconnect-notifier|代替機能を開発中。|
remove-attachment|不要になりました。添付ファイルを変数として保存できます。|
remove-property|新しいメッセージモデルではプロパティが使用されなくなりました。Mule メッセージからの属性は変数に保存できます。|
response|排除されました。不要になりました。|
request-reply|Mule 4 では、すべてのコネクタで request-reply がサポートされなくなります。「request-reply」動作があったコネクタは、JMS の consume 操作など、「request-reply」操作をビルトインで提供します。|
resin-transaction-mamanger|代替機能を開発中。|
rollback-exception-strategy|on-error-propagate 戦略を使用する error-handler を使用します。|
scatter-gather[‘threading-profile’]|Mule 4 は非ブロックなので不要になりました。 |
seda-model|Mule 4 では SEDA キューがなくなりました。Mule 4 の実行エンジンは非ブロックです。|
service|フローを使用します。|
set-attachment|不要になりました。添付ファイルを変数として保存できます。|
set-property|新しいメッセージモデルではプロパティが使用されなくなりました。Mule メッセージからの属性は変数に保存できます。|
set-session-variable|セッション変数は削除されました。ユーザはトランスポートの境界を越えて明示的にヘッダーを渡す必要があります。|
simple-in-memory-queue-store|新しい VM コネクタ (開発中) を使用します。|
simple-service|フローを使用します。|
simple-text-file-store|オブジェクトストアモジュール拡張機能を使用してカスタムストアを作成します。|
singleton-object|Java モジュールまたは Spring モジュールを使用します。|
spring-object|Java モジュールまたは Spring モジュールを使用します。|
synchronous-processing-strategy|フローコンポーネントの実行に関連する動作は、4.x のフローと同じですが、必ずしも 3.x と同じスレッドでは実行されません。|
transactional scope|“try” スコープに置き換わりました。|
username-password-filter|代替機能を開発中。|
validator|排除されました。|
weblogic-transaction-manager|代替機能を開発中。|
websphere-transaction-manager|代替機能を開発中。|
*-all-strategy|排除されました。|
*-entry-point-resolver|Java モジュールを使用します (開発中)。|
*-filter|代替機能を開発中。|
*-interceptor|代替機能を開発中。|
*-message-info-mapping|代替機能を開発中。|
*-point-resolver-set|Java モジュールを使用します (開発中)。|
*-router|排除されました。|
*-threading-profiled|トランスポート名前空間に属するようになりました。|
*-transformer|代替機能を開発中。|
|===

== Mule モジュールおよびコネクタ

Mule 4 には、Mule 3 で使用できるすべてのコネクタのサブセットが含まれています。次の表では、廃止/削除された Mule 3.x モジュールと、Mule 4.0 での置き換え方法を示しています。その他の Select および Premium コネクタはすべて開発中です。

[%header,cols="30,70"]
|===
Mule 3.x のモジュール| Mule 4.0 の代替法
|Ajax	| APIkit + 標準 REST を使用します。
|Atom	| 代わりに HTTP + DataWeave が導入されました。
|Axis	| WS Consumer/APIkit for SOAP を使用します。
|Drools|排除されました。
|BPM|Pega/Appian for BPM への接続性が提供されました。
|EJB|排除されました。
|Guice|排除されました。
|jBPM|MuleSoft では、BPM 向けに Paga または Appian への接続を提供するようになりました。
|Jetty	| 新しい HTTP モジュールを使用します。
|OGNL	| 代わりに DataWeave 式言語、互換モジュールには MEL が導入されました。
|Patterns|排除されました。代わりにフローを使用します。
|Quartz	| <poll> を使用します。
|RSS	| HTTP + DataWeave を使用します。
|SXC	| DataWeave を使用します。
|Tomcat 	| 新しい組み込みモードを開発中です。
|Servlet	| 新しい組み込みモードを開発中です。
|Stdio|排除されました。
|UDP	| ソケットを使用します。
|XMPP|排除されました。
|===

== 関連情報

* xref:mule-runtime-updates.adoc[Mule 4 の新機能]
* xref:index.adoc[Mule Runtime]
