= Raise Error コンポーネント
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Mule, esb, Studio, 生成, エラー

このコアコンポーネントは、障害が発生したかのように Mule エラーを生成し、その説明および種別をカスタマイズできます。

このコンポーネントは、`MULE:SECURITY` や `MULE:CONNECTIVITY` などのコアランタイムエラー、またはカスタムエラーを発生させるためにのみ使用します。
別のコネクタや `FILE:FILE_NOT_FOUND` や `JSON:INVALID_SCHEMA` などのモジュールからエラーを発生させることはできません。コネクタの既存の名前空間を使用することはできません。

コアランタイムエラー種別では、暗黙的な名前空間および識別子を使用する必要があり、エラーの説明メッセージのみカスタマイズできます。 +
カスタムエラー種別では、新しい名前空間を宣言します。エラー種別の名前空間は、エラーの起源を特定するのに役立ちます。 +
コネクタまたはモジュールでは定義済みの名前空間があるため、これらから既存の名前空間を使用することはできません。
`raise-error` で使用することでカスタム名前空間を宣言した場合は、他の `raise-error` コンポーネントおよびカスタム種別で使用できます。

次のフロー例では、転送量が使用可能な残量を超えた場合に `ACCOUNT:INSUFFICIENT_FUNDS` エラーが
発生し、転送が行われるのを
防ぎます。さらに、障害の詳細を含む式を提供することで、
動的な説明を生成します。

.例: フローの XML 設定
[source,xml,linenums]
----
<flow name="raise-error-example-flow">
  <http:request url="https://unsecurebank.com/balance" target="balance"/>
  <choice>
      <when expression="#[payload.amount > vars.balance]">
          <raise-error type="ACCOUNT:INSUFFICIENT_FUNDS" description="#['Cannot transfer $(payload.amount) since only $(vars.balance) are available.']"/>
      </when>
  </choice>
  <http:request url="https://unsecurebank.com/transfer"/>
</flow>
----

この例では、静的な説明が含まれるエラーを生成し、`ORDER` 名前空間を使用する
カスタム種別であることがわかります。

[source,xml,linenums]
----
 <raise-error description="Email is invalid. Cannot complete transaction." type="ORDER:INVALID_DATA"/>
----

== エラー生成設定

[%header,cols="1,1,2,2"]
|===
| 項目 | 値 | 説明 | 例

| 説明 | String (文字列) または DataWeave 式 | エラーの説明を指定します。 |
`description="Invalid email. Cannot complete transaction."`

| 型 | String (文字列) | エラーの種別を指定します。 |
`type="ORDER:INVALID_DATA"`

|===

== 関連情報
xref:mule-error-concept.adoc[Mule エラー]