= トランザクションの管理
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: トランザクション, 管理, 区分, jms, jdbc, vm, データベース, resource (リソース), xa, tx

トランザクションとは、結果が不確定になることができない Mule アプリケーションの操作です。フローの一連のステップが 1 つの単位として成功または失敗する必要がある場合、Mule はトランザクションを使用して、それらのステップを単位として区分します。たとえば、トランザクションを使用して、データベースに情報をコミットするためのフロー内の複数のステップをカプセル化することができます。このようなシナリオでは、コミット (トランザクション) は、全体が完了 (成功) するか、不完全に終了 (失敗) するかのどちらかとなります。部分的に完了しても、コミットは失敗となります。トランザクションが失敗すると、一部だけで部分的な完了とならないように Mule は操作をトランザクション内でロールバックします。

Try スコープを使用すると、[General (一般)] タブからトランザクションを設定できます。この設定の XML は次のようになります。

.XML の例: Try スコープでのトランザクションの設定

次の例では、Try スコープによってデータベース操作と VM 操作を含むトランザクションを区分しています。Try スコープ内でエラーが発生した場合は、両方が適用されるか、またはどちらも適用されません。

[source,xml,linenums]
----
include::{examplesdir}/transaction-management_1.xml[]
----

トランザクションをメッセージソースから開始することもできます。この場合は、フロー全体が 1 つのトランザクションとなります。この方法は、メッセージングコネクタを使用して、メッセージングの処理中に問題が発生した場合にはメッセージをコンシュームしないようにして、後で (ロールバックによって) 再試行できるようにしたいときに便利です。

.XML の例: メッセージソースでのトランザクションの設定

[source,xml,linenums]
----
include::{examplesdir}/transaction-management_2.xml[]
----

Studio では、次のコネクタの操作には [Advanced (詳細)] タブがあり、トランザクションをセットアップすることができます。

* JMS:
 ** リスナは、ローカルおよび XA トランザクション種別をサポートします。設定すると、フロー全体が 1 つのトランザクションとして扱われます。
 ** Consume 操作と Publish 操作はトランザクションをサポートします。
* VM:
 ** リスナは、ローカルおよび XA トランザクション種別をサポートします。設定すると、フロー全体が 1 つのトランザクションとして扱われます。
 ** Consume 操作と Publish 操作はトランザクションをサポートします。
* Database:
 ** すべての Database 操作はトランザクションをサポートします。

Mule フローは、非トランザクションコネクタ (HTTP など) で開始して、フロー内でトランザクションを必要する場合があります。たとえば、Mule フローで外部 Web サービスから情報を受け入れ、クレジットカードに請求してインボイス情報をデータベースに保存する前にデータを変換するとします。この場合は Try スコープを使用して、クレジットカードへの請求操作とデータベースへのコミット操作をラップすることでトランザクションをセットアップすれば、常に完全な成功または完全な失敗とロールバックのどちらかの結果になることを保証できます。

== トランザクションのアクション

トランザクションアクション (`transactionalAction`)

* ALWAYS_BEGIN: メッセージの受信時に常に新しいトランザクションを開始します。トランザクションがすでに存在する場合は例外をスローします。トランザクションをサポートするリスナにはこのオプションがあります。

* ALWAYS_JOIN: メッセージの受信時に常にトランザクションが進行中であると想定します。トランザクションがない場合は例外がスローされます。トランザクションをサポートする操作にはこのオプションがあります。

* BEGIN_OR_JOIN: メッセージの受信時にトランザクションが進行中である場合、可能であればトランザクションを結合します。可能でなければ新しいトランザクションを開始します。トランザクションをサポートするスコープにはこの設定があります。

* JOIN_IF_POSSIBLE: 現在のトランザクションが使用可能な場合、そのトランザクションを結合します。可能でなければトランザクションは作成されません。トランザクションをサポートする操作にはこの設定があります。

* INDIFFERENT: アクションをトランザクションとして扱いません。トランザクションをサポートするスコープにはこの設定があります。

* NONE: トランザクションに関与しません。トランザクションをサポートするリスナにはこの設定があります。

* NOT_SUPPORTED: 存在するトランザクションの外部で実行します。トランザクションをサポートする操作にはこの設定があります。トランザクションをサポートするスコープにはこの設定があります。

== トランザクション種別

Mule は、単一リソース (ローカル、デフォルト) および拡張アーキテクチャ (`XA`) トランザクション種別 (`transactionType`) をサポートします。それぞれの種別の特徴は次の通りです。

* 単一リソーストランザクション (ローカル)
 ** 1 つのリソースとの間でのみメッセージを送受信します。
 ** XA よりパフォーマンスが高くなります。

* XA トランザクション
 ** 複数のリソースとの間でメッセージを送受信します。
 ** 2 段階のコミットアルゴリズムを使用します。
 ** コネクタが XA に対応している必要があります。
 ** ローカルより遅くなりますが、信頼性は高くなります。
